import { useCallback, useEffect, useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { api } from '../lib/api';
import Modal from '../components/Modal';

const empty = { student_id: '', course_id: '', session: '2026/2027', semester: 'first', status: 'enrolled' };
export default function EnrolmentsPage() {
  const { isAdmin } = useAuth(); const [items, setItems] = useState([]); const [students, setStudents] = useState([]); const [courses, setCourses] = useState([]); const [form, setForm] = useState(empty); const [showForm, setShowForm] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async () => { try { const config = { params: { per_page: 100 } }; const [enrolments, courseList] = await Promise.all([api('/enrolments', config), api('/courses', config)]); setItems(enrolments.data); setCourses(courseList.data); if (isAdmin) { const studentList = await api('/students', config); setStudents(studentList.data); } } catch (e) { setError(e.message); } }, [isAdmin]);
  // Fetch the role-scoped collections whenever the signed-in role changes.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { load(); }, [load]);
  const submit = async (event) => { event.preventDefault(); try { await api('/enrolments', { method: 'POST', data: { ...form, student_id: Number(form.student_id), course_id: Number(form.course_id) } }); setShowForm(false); setForm(empty); await load(); } catch (e) { setError(Object.values(e.errors ?? {}).flat()[0] ?? e.message); } };
  const remove = async (id) => { if (!window.confirm('Remove this enrolment?')) return; try { await api(`/enrolments/${id}`, { method: 'DELETE' }); await load(); } catch (e) { setError(e.message); } };
  return <section className="panel"><div className="page-heading"><div><h1>{isAdmin ? 'Enrolments' : 'My enrolments'}</h1><p>{isAdmin ? 'Assign students to courses' : 'Your course history'}</p></div>{isAdmin && <button onClick={() => { setForm(empty); setError(''); setShowForm(true); }}>New enrolment</button>}</div>{error && <div className="alert error-alert">{error}</div>}
    {showForm && <Modal title="New enrolment" onClose={() => setShowForm(false)}><form className="form-card modal-form" onSubmit={submit}><label>Student<select required value={form.student_id} onChange={(e) => setForm({ ...form, student_id: e.target.value })}><option value="">Select student</option>{students.map((student) => <option key={student.id} value={student.id}>{student.name} ({student.matric_no})</option>)}</select></label><label>Course<select required value={form.course_id} onChange={(e) => setForm({ ...form, course_id: e.target.value })}><option value="">Select course</option>{courses.map((course) => <option key={course.id} value={course.id}>{course.code} — {course.title}</option>)}</select></label><label>Session<input required pattern="\d{4}/\d{4}" value={form.session} onChange={(e) => setForm({ ...form, session: e.target.value })} /></label><label>Semester<select value={form.semester} onChange={(e) => setForm({ ...form, semester: e.target.value })}><option value="first">First</option><option value="second">Second</option></select></label><label>Status<select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}><option value="enrolled">Enrolled</option><option value="completed">Completed</option><option value="dropped">Dropped</option></select></label><div className="form-actions"><button type="button" className="secondary" onClick={() => setShowForm(false)}>Cancel</button><button>Save enrolment</button></div></form></Modal>}
    <div className="table-wrap"><table><thead><tr><th>Student</th><th>Course</th><th>Session</th><th>Semester</th><th>Status</th>{isAdmin && <th>Actions</th>}</tr></thead><tbody>{items.map((item) => <tr key={item.id}><td>{item.student.name}</td><td><strong>{item.course.code}</strong> — {item.course.title}</td><td>{item.session}</td><td>{item.semester}</td><td><span className={`badge ${item.status}`}>{item.status}</span></td>{isAdmin && <td><button className="danger" onClick={() => remove(item.id)}>Remove</button></td>}</tr>)}</tbody></table>{!items.length && <div className="empty">No enrolments found.</div>}</div>
  </section>;
}
